[build]
  publish = "build/web"
  command = """
    if [ -d "flutter" ]; then rm -rf flutter; fi &&
    git clone https://github.com/flutter/flutter.git --branch stable &&
    export PATH="$PATH:$PWD/flutter/bin" &&
    flutter precache &&
    flutter build web
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 